:ems:
  :ems_ibm_cloud_power_virtual_servers:
    :api_endpoint_overrides:
      :dal12: us-south.power-iaas.cloud.ibm.com
    :event_handling:
      :event_groups:
        :power:
          :critical:
          - IBM_CLOUD_POWER_VIRTUAL_SERVERS_instance_power_on
          - IBM_CLOUD_POWER_VIRTUAL_SERVERS_instance_power_off

:ems_refresh:
  :ibm_vpc:
    :refresh_interval: 15.minutes
  :ems_refresh_worker_ibm_cloud_object_storage:
    :refresh_interval: 15.minutes
  :ibm_cloud_power_virtual_servers:
    :refresh_interval: 15.minutes
    :storage_types:
    - :description: Tier 1 (NVMe-based flash storage)
      :state: active
      :type: tier1
    - :description: Tier 3 (SSD flash storage)
      :state: active
      :type: tier3
    - :description: SSD (Legacy)
      :state: active
      :type: ssd-legacy
    - :description: Standard (Legacy)
      :state: active
      :type: standard-legacy
:log:
  :level_ibm_cloud: info
:workers:
  :worker_base:
    :event_catcher:
      :event_catcher_ibm_cloud_power_virtual_servers:
        :poll: 20.seconds
    :queue_worker_base:
      :ems_refresh_worker:
        :ems_refresh_worker_ibm_cloud_power_virtual_servers: {}
        :ems_refresh_worker_ibm_cloud_vpc: {}
        :ems_refresh_worker_ibm_cloud_object_storage: {}